### ISSUE TITLE
ssh_args ignored in jessie (Upstream bug)

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-rsnapshot#10]
This is fixed with rsnapshot 1.4.0. And works as expected.

If this version is installed, ssh_args should not disabled. Or should  ansible-rsnapshot install the new version (testing)?

Commit:
https://github.com/debops/ansible-rsnapshot/commit/738095700feec3932c269e7a5e950b2db82377d9

**Comment by drybjed** [comment]
`debops.rsnapshot` can check the version of `rsnapshot` installed on the host and enable/disable `ssh_args` using `version_compare()` Ansible filter.

Instead of installing `rsnapshot` directly from Debian Testing, you should consider backporting it to Debian Stable and either put it in your local APT repository, or upload to http://backports.debian.org/, prefrerably by contacting with the maintainer of `rsnapshot` Debian package.

**Comment by Gomez** [comment]
Thanks @drybjed. I will create a PR the next days with ```version_compare()```.
